-- AlterTable
ALTER TABLE "Branch"
ADD COLUMN "scheduleStartTime" TEXT NOT NULL DEFAULT '09:00',
ADD COLUMN "scheduleEndTime" TEXT NOT NULL DEFAULT '18:00',
ADD COLUMN "graceLateMins" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "expectedWorkMins" INTEGER NOT NULL DEFAULT 480;
